language: rust

matrix:
  include:
    - name: linux-pkgconfig
      os: linux
      rust: stable
      addons:
        apt:
          packages:
            - libusb-1.0-0-dev
      before_script:
        - pkg-config --libs libusb-1.0
        - pkg-config --modversion libusb-1.0
      script:
        - cargo test --verbose --all
    - name: linux-no-pkgconfig
      os: linux
      rust: stable
      addons:
        apt:
          packages:
            - libudev-dev
      before_script:
        - pkg-config --libs libudev
        - pkg-config --modversion libudev
      script:
        - cargo test --verbose --all
    - name: osx
      os: osx
      rust: stable
      script:
        - cargo test --verbose --all
    - name: windows
      os: windows
      rust: stable
      env:
        - VCPKG_ROOT: $TRAVIS_BUILD_DIR/vcp
        - VCPKG_PLATFORM: x64-windows-static
      before_script:
        - git clone https://github.com/Microsoft/vcpkg.git vcp
        - if [ $TRAVIS_OS_NAME == "windows" ] ; then  vcp/bootstrap-vcpkg.bat; else vcp/bootstrap-vcpkg.sh; fi
        - vcp/vcpkg.exe install libusb:$VCPKG_PLATFORM
      script:
        - cargo test --verbose --all
