language: rust
rust: nightly

before_install:
  - cp /etc/apt/sources.list /tmp/sources.list
  - grep -v rabbitmq /tmp/sources.list | sudo tee /etc/apt/sources.list
  - sudo apt-get update -q
  - sudo apt-get install -y build-essential libudev-dev
  - wget https://github.com/libusb/libusb/archive/v1.0.19.tar.gz -O libusb-1.0.19.tar.gz
  - tar -zxvf libusb-1.0.19.tar.gz
  - cd libusb-1.0.19 && ./autogen.sh && ./configure --prefix=/usr && make && sudo make install
  - pkg-config --list-all
  - pkg-config --libs libusb-1.0
  - pkg-config --modversion libusb-1.0
