language: rust

matrix:
  include:
    - name: linux-pkgconfig
      os: linux
      rust: stable
      addons:
        apt:
          packages:
            - libusb-1.0-0-dev
      before_script:
        - pkg-config --libs libusb-1.0
        - pkg-config --modversion libusb-1.0
      script:
        - cargo test --verbose --all
    - name: osx
      os: osx
      rust: stable
      script:
        - cargo test --verbose --all
