[package]

name = "libusb1-sys"
version = "0.3.0"
authors = ["David Cuddeback <david.cuddeback@gmail.com>"]
description = "FFI bindings for libusb."
license = "MIT"
homepage = "https://github.com/a1ien/libusb1-sys"
repository = "https://github.com/a1ien/libusb1-sys.git"
readme = "README.md"
keywords = ["usb", "libusb", "hardware", "bindings"]
edition = "2018"

build = "build.rs"

[dependencies]
libc = "0.2"

[build-dependencies]
cc = "1.0"
pkg-config = "0.3"
