[package]

name = "libusb-sys"
version = "0.2.3"
authors = ["David Cuddeback <david.cuddeback@gmail.com>"]
description = "FFI bindings for libusb."
license = "MIT"
homepage = "https://github.com/dcuddeback/libusb-sys"
repository = "https://github.com/dcuddeback/libusb-sys.git"
readme = "README.md"
keywords = ["usb", "libusb", "hardware", "bindings"]

build = "build.rs"

[dependencies]
libc = "0.2"

[build-dependencies]
gcc = "0.3"
