[package]

name = "libusb-sys"
version = "0.0.1"
authors = ["David Cuddeback <david.cuddeback@gmail.com>"]
description = "Rust bindings for libusb 1.0."
license = "MIT"
homepage = "https://github.com/dcuddeback/libusb-sys"
repository = "https://github.com/dcuddeback/libusb-sys.git"

build = "build.rs"
links = "usb-1.0"

[build-dependencies]
pkg-config = "0.3.0"
