[package]

name = "libusb-sys"
version = "0.1.1"
authors = ["David Cuddeback <david.cuddeback@gmail.com>"]
description = "Rust bindings for libusb 1.0."
license = "MIT"
homepage = "https://github.com/dcuddeback/libusb-sys"
repository = "https://github.com/dcuddeback/libusb-sys.git"
readme = "README.md"
keywords = ["usb", "libusb", "hardware", "bindings"]

build = "build.rs"
links = "usb-1.0"

[dependencies]
libc = "0.1.5"

[build-dependencies]
pkg-config = "0.3.2"
