name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            apt: 'libusb-1.0-0-dev'

          - os: ubuntu-latest
            apt: 'libudev-dev'

          - os: macos-latest

          - os: windows-latest

          - os: windows-latest
            vcpkg: x86-windows-static-md
            rust: stable-i686-pc-windows-msvc

          - os: windows-latest
            vcpkg: x64-windows-static-md
            rust: stable-x86_64-pc-windows-msvc

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install
        if: ${{ contains(matrix.os, 'ubuntu') }}
        run: sudo apt-get install --no-install-recommends -y ${{ matrix.apt }}

      - name: Install additional rust toolchain
        if: ${{ matrix.rust != '' }}
        run: rustup toolchain install ${{ matrix.rust }} && rustup default ${{ matrix.rust }}

      - name: Install vcpkg
        if: ${{ matrix.vcpkg != '' }}
        run: C:/vcpkg/vcpkg integrate install && C:/vcpkg/vcpkg install libusb:${{ matrix.vcpkg }}

      - name: Build
        run: cargo build --workspace -vv --examples

      - name: Run tests
        run: cargo test --workspace --verbose --all
